pkg: de-lint podnetwork package
Fixed errors caught by golangci-lint:

pkg/podnetwork/tunneler/routing/workernode.go:40:2: `interfaceIndex`
is unused (deadcode)
        interfaceIndex = 1
        ^
pkg/podnetwork/tuntest/util.go:177:20: Error return value of
`s.server.Shutdown` is not checked (errcheck)
                s.server.Shutdown(context.Background())
                                 ^
pkg/podnetwork/tunneler/routing/keepalive.go:180:11: Error return
value of `ns.Run` is not checked (errcheck)
                                ns.Run(func() error {
                                      ^
pkg/podnetwork/tunneler/routing/keepalive.go:275:22: Error return
value of `httpServer.Shutdown` is not checked (errcheck)
                httpServer.Shutdown(context.Background())
                                   ^
pkg/podnetwork/workernode.go:26:2: `podNodeIP` is unused (structcheck)
        podNodeIP     net.IP

pkg/podnetwork/tuntest/util.go:134:2: SA1006: printf-style function
with dynamic format string and no further arguments should use
print-style function instead (staticcheck)
        fmt.Fprintf(w, string(h))
        ^
Fixes #32
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>